export const hotelTypes = [
  "Hotel",
  "Resort",
  "Villa",
  "Motel",
  "Budget",
  "Boutique",
  "Beach Resort",
  "Camping",
  "Hostel",
  "Apartment",
  "Condo",
  "Cabin",
  "Luxury",
  "Ski Resort",
  "Business",
  "Family",
  "Romantic",
  "Hiking Resort",
  "Golf Resort",
  "All Inclusive",
  "Self Catering",
];

export const roomFacilities = [
  "Free WiFi",
  "Parking",
  "Airport Shuttle",
  "Family Rooms",
  "Non-Smoking",
  "Outdoor Pool",
  "Private Pool",
  "Spa",
  "Fitness Center",
  "Gym",
  "Laundry",
  "Breakfast",
  "Tennis Court",
  "Basketball Court",
  "Pet Friendly",
  "Meeting Room",
];

export const hotelFacilities = [
  "Free WiFi",
  "Parking",
  "Airport Shuttle",
  "Family Rooms",
  "Non-Smoking",
  "Outdoor Pool",
  "Private Pool",
  "Spa",
  "Fitness Center",
  "Gym",
  "Laundry",
  "Breakfast",
  "Tennis Court",
  "Basketball Court",
  "Pet Friendly",
  "Meeting Room",
];